### ISSUE TITLE
Why does Fury serialized byte array significantly larger compared to Kryo?

### ISSUE THREAD

**Issue by cdxf** [alipay/fury#912] opened 2023-09-17 04:42 UTC
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**

I setup a simple test to compare Fury and Kryo byte array output size:
Result:
- Fury generate 280044 bytes;
- Kryo generate 150030 bytes;

Yes, it is just a simple synthetic benchmark, but in my real use case (real entities using Hibernate), Fury usually generates byte arrays that is 2x larger than Kryo.
I also registered same classes for both Fury and Kryo.

**Expected behavior**
Serialized Byte array should have similar size.

**To Reproduce**

```
public record Student(String name) {
}

public class FurySerializer implements Serializer<Object> {
    private final static Logger logger = LoggerFactory.getLogger(FurySerializer.class);

    private final static ThreadSafeFury fury = new ThreadLocalFury(classLoader -> {
        Fury f = Fury.builder()
                .requireClassRegistration(false)
                .withRefTracking(true)
                .withAsyncCompilation(false)
                .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
                .withJdkClassSerializableCheck(false)
                .withIntCompressed(true)
                .withLongCompressed(true)
                .withLanguage(Language.JAVA).withClassLoader(classLoader).build();
        configureFury(f);
        return f;
    });
    public FurySerializer(ClassLoader loader) {

    }

    public FurySerializer() {
    }

    private static void configureFury(Fury fury) {
        // Just a list of registered class I am using
    }

    @Override
    public ByteBuffer serialize(Object object) throws SerializerException {
        try {
            byte[] serialize = fury.serialize(object);
            return ByteBuffer.wrap(serialize);
        } catch (Exception e) {
            logger.error("SerializerException in read", e);
            throw new SerializerException("SerializerException in read");
        }
    }

    @Override
    public Object read(ByteBuffer binary) throws ClassNotFoundException, SerializerException {
        try {
            return fury.deserialize(binary);
        } catch (Exception e) {
            logger.error("SerializerException in read", e);
            throw new SerializerException("SerializerException in read");
        }
    }

    @Override
    public boolean equals(Object o, ByteBuffer byteBuffer) throws ClassNotFoundException, SerializerException {
        return o.equals(read(byteBuffer));
    }
}


@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class IntegrationTest {
    ArrayList<Student> students;

    @BeforeAll
    public void setup() {
        students = new ArrayList<>(10000);
        for (int i = 0; i < 10000; i++) {
            students.add(new Student(String.valueOf(System.currentTimeMillis())));
        }
    }

    @Test
    public void testFury() {
        FurySerializer furySerializer = new FurySerializer();
        ByteBuffer serialize = furySerializer.serialize(students);
        System.out.println("Size:" + serialize.limit());
    }

    @Test
    public void testKryo() {
        KryoSerializer kryoSerializer = new KryoSerializer();
        ByteBuffer serialize = kryoSerializer.serialize(students);
        System.out.println("Size:" + serialize.limit());

    }
}

```
**Environment (please complete the following information):**
- JDK 20
- Fury snapshot 0.2.0

**Comment by chaokunyang** [comment] 2023-09-17 10:52
@cdxf This is a known issue, the serialization for collection/map didn't use the possible homogeneous information. For example, all collection elements are not null in most cases and all collection elements are same type mostly. But currently fury didn't use this information. I'm trying to improve it, but the compaibility between  fury jit and interpreter mode take lots of work, it still some time before we can support this optimization.

And if you serialize IntegrationTest object directly, you will find that it take only `210071` bytes, this is because fury jit can determine the actual element type in advance  since record class is final.

**Comment by chaokunyang** [comment] 2023-09-17 11:54
After a detailed test, I found is't caused by Fury class version check, which write 
 4 bytes to validate class consistentcy. If you disable it by `io.fury.Fury.FuryBuilder#withClassVersionCheck(false)`, fury serialized size is about `170067` size, which is close to kryo size.

**Comment by cdxf** [comment] 2023-09-17 13:28
Thanks for your response, in my case (Hibernate Entities with deep object graph and multiple collections), Kryo still produces smaller byte arrays, but the perf gain is worth the tradeoff. Hope can be improved in further version.

```
Comparison Results:

Fury (withClassVersionCheck enabled):
Size: 232259 bytes
Avg: 0.70916 ms per serialize/deserialize cycle

Fury
Size: 225259 bytes
Avg: 0.69807 ms per serialize/deserialize cycle

Kryo
Size:174611 bytes
Avg: 2.21102 ms per serialize/deserialize cycle
```

**Comment by chaokunyang** [comment] 2023-10-07 11:11
@cdxf @trydofor with our optimization in #927 #945, now fury serialized is `170077`, which is smaller than kryo. Please try it out:
```xml
<dependency>
    <groupId>org.furyio</groupId>
    <artifactId>fury-core</artifactId>
    <version>0.2.0-alpha.1</version>
</dependency>
```

`v0.2.0` will be released in next days

**Comment by chaokunyang** [comment] 2023-10-08 07:33
`v0.2.0` has been released, pelase try it out.

**Closed** 2023-10-08 07:33 UTC
Labels: bug

**Comment by cdxf** [comment] 2023-10-11 17:59
I tested again using Fury snapshot 0.3.
```
array size = 10000
Fury Size:170008
Kryo Size:150027

array size = 100000
Fury Size:1700009
Kryo Size:1500027

array size = 1000000
Fury Size:17000009
Kryo Size:15000027
```

**Comment by cdxf** [comment] 2023-10-11 18:15
The configuration:
```
        Fury f = Fury.builder()
                .requireClassRegistration(false)
                .withRefTracking(true)
                .withAsyncCompilation(false)
                .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
                .withClassVersionCheck(false)
                .withJdkClassSerializableCheck(false)
                .withIntCompressed(true)
                .withLongCompressed(true)
                .withLanguage(Language.JAVA).withClassLoader(classLoader).build();
```
Here is the bin file generated from both fury and kryo with array size = 100 in case you are curious
[test.zip](https://github.com/alipay/fury/files/12873331/test.zip)

**Comment by chaokunyang** [comment] 2023-10-12 16:46
> I tested again using both Fury 0.2 and snapshot 0.3, same result for both version (using the first example):
> 
> ```
> array size = 10000
> Fury Size:170008
> Kryo Size:150027
> 
> array size = 100000
> Fury Size:1700009
> Kryo Size:1500027
> 
> array size = 1000000
> Fury Size:17000009
> Kryo Size:15000027
> ```

Kryo5 disabled reference by defaultl ,maybe you should enable it since you enable it for fury. When it's enabled, fury is 6% larger, kryo optimize ascii string by one byte, it's not good for performance optimization, we have no plan for such optimization.
